# vim: set noai nosi ts=2 sw=2 syntax=yaml


- pack:
    version: 1.16.5
    description: "franz custom advancements for mc 1.16.5"

- category:
  - root: "Mining"
    description: "A story underground"
    id: franz_advancements:mining
    task:
      - in_inv: minecraft:wooden_pickaxe
    icon: minecraft:netherite_pickaxe
    nbt:
      Enchantments:
        - lvl: 1
        - id: "minecraft:mending"
    background: "minecraft:textures/gui/advancements/backgrounds/stone.png"

  - name: "Stone Age"
    description: ""
    id: stone_age
    task:
      - trigger: minecraft:inventory_changed
        conditions:
          items:
            - item: minecraft:bedrock
              count: 64
      - in_inv: minecraft:bedrock
      - in_inv:
        - minecraft:bedrock: 64
        - minecraft:cobblestone: 32
        - minecraft:stone_stairs
      - break_tool: minecraft:stone_pickaxe
    icon: minecraft:wooden_pickaxe
    parent: root
#   frame: "task"
#   pop_up: true
#   chat: true
#   hidden: false

- category:
  - root: "Redstone"
    description: "A story full of blockupdates and blockevents"
    id: franz_advancements:redstone
    task:
      - in_inv: minecraft:redstone
    icon: "minecraft:sticky_piston"
    background: "minecraft:textures/block/redstone_ore.png"

  - name: "Compact it"
    description: "Get a rs block!"
    id: compact_it
    task:
      - - in_inv: minecraft:redstone_ore
        - break_tool: minecraft:stone_sword
      - - in_inv: minecraft:redstone_block
        - break_tool: minecraft:netherite_pickaxe
    icon: minecraft:redstone_ore
    parent: root
    hidden: true

